### ISSUE TITLE
Make it work with hosting rewrites if possible please

### ISSUE THREAD

**Issue by Youdaman** [googleapis/nodejs-firestore-session#189]
I pasted the example given in the readme into a file called `session.js` and replaced:

- `app.get('/'...` with `app.get('/api/session'...`
- `app.listen...` with `module.exports = app`

And then setup and endpoint in `index.js` like so:

```
const session = require('./session')
exports.session = functions
  .https.onRequest(session)
```

This works via:

https://us-central1-MY-PROJECT.cloudfunctions.net/session/api/session

And also in the local emulator via:

http://localhost:3000/api/session

As long as the following rewrite is present in `firebase.json`:

```
"rewrites": [
      {
        "source": "/api/session",
        "function": "session"
      },
...
```

However if I try to call the deployed/live version via a domain that I've setup with hosting:

https://MY-DOMAIN/api/session

Then the count never gets incremented and you always see "Views 0"

My guess is the rewrite is screwing with how the session gets saved/loaded?

**Comment by schmidt-sebastian** [comment]
Sorry I don't know anything about this repo.
