### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-firestore-session#4]

**Comment by fhinkel** [comment]
Is this really blocking?

**Comment by JustinBeckwith** [comment]
It is if it impacts the design of the API.  90% of the work is done in #7, and I want to make sure the API design won't change as a side effect of being typescripty :)

**Comment by JustinBeckwith** [comment]
@jkwlui @fhinkel I think I'm blocked on #2 here :)

**Comment by fhinkel** [comment]
Fixed with https://github.com/googleapis/nodejs-firestore-session/pull/7
